### ISSUE TITLE
missing return in a function expected to return 'string'

### ISSUE THREAD

**Issue by rubnov** [fxm90/GradientLoadingBar#25]
My project uses GradientLoadingBar and I've just ran `pod update` and got the version bump to 2.2.1. 

However, when building with Xcode 13, an error is generated:

```
Pods/GradientLoadingBar/GradientLoadingBar/Classes/ViewModel/NotchGradientLoadingBarViewModel.swift:81:5: 
error: missing return in a function expected to return 'String'
```

Had to revert back to 2.1.1 unfortunately...

**Comment by fxm90** [comment]
Thanks for reporting 🙏 Seems like Xcode unfortunately doesn't validate the `else` part of `if targetEnvironment(simulator)`, when building for the simulator 🙈 

I've just released version `2.2.2` containing a fix.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/17249312/136049201-511c3abb-80f7-4b57-830c-96b041f6ec6e.png">

**Comment by fxm90** [comment]
FYI @OnurVar you might want to update as well.

**Comment by rubnov** [comment]
`pod update` still gets me 2.2.1. Are you sure that 2.2.2 is published on Cocoapods?  
my podfile: 
```
    pod 'GradientLoadingBar', '~> 2.0'
```

**Comment by fxm90** [comment]
[The Cocoapods website](https://cocoapods.org/pods/GradientLoadingBar) says latest version is `2.2.2`.

Maybe try running `pod cache clean --all` before running `pod update` ?
